<?php
function uploadfile_menu() {
  $items = array();
  
  $items['test_file'] = array(
    'title' => 'test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uploadfile_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function uploadfile_form($form, &$form_state) {
  $form = array();
  $form['file'] = array(
    	'#type' => 'file',
    	'#title' => t('Image'),
    	'#description' => t('Upload a file, allowed extensions: jpg, jpeg, png, gif'),
      //'file_validate_size' => array(1024*1024),
  );
// $form['file'] = array(
//'#title' => t('Photo (Max size 2 MB)'),
//'#type' => 'managed_file',
//'#description' => t('xvxcds'),
//'#default_value' => variable_get('photo', ''),
//'#upload_location' => 'public://photo_images/',
// '#upload_validators' => array(
//'file_validate_size' => array(1024*1280*800),
//'file_validate_extensions' => array('gif jpg jpeg png'),
//// Pass the maximum file size in bytes
//), );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function uploadfile_form_validate($form, &$form_state) {
  $file = file_save_upload('file', array(
  	'file_validate_is_image' => array(),
  	'file_validate_extensions' => array('png gif jpg jpeg'),
    'file_validate_size' => array(1024*1024*2),
  ));
  if ($file) {
    if ($file = file_move($file, 'public://')) {
      $form_state['values']['file'] = $file;
    }
    else {
      form_set_error('file', t('Failed to write the uploaded file the site\'s file folder.'));
    }
  }
  else {
    form_set_error('file', t('No file was uploaded.'));
  }
}

function uploadfile_form_submit($form, &$form_state) {
  $file=$form_state['values']['file'];
 
  unset($form_state['values']['file']);
  $file->status = FILE_STATUS_PERMANENT;
  file_save($file);
  drupal_set_message(t('The form has been submitted and the image has been saved, filename: @filename.', array('@filename' => $file->filename)));
}
?>